 # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(290, 85)
        MainWindow.setStyleSheet(u"QWidget {\n"
                                 "                color: black;\n"
                                 "                background-color: #FFF;\n"
                                 "                font-family: Rubik;\n"
                                 "                font-size: 14pt;\n"
                                 "                font-weight: 300;\n"
                                 "                }\n"
                                 "\n"
                                 "                QPushButton {\n"
                                 "                background-color: #FFF;\n"
                                 "                border: 1px #888;\n"
                                 "                border-style: solid;\n"             
                                 "                }\n"
                                 "\n"
                                 "                QPushButton:hover {\n"
                                 "                background-color: #DCDCDC;\n"
                                 "                }\n"
                                 "\n"
                                 "                QPushButton:pressed {\n"
                                 "                background-color: #808080;\n"
                                 "                }\n"
                                 "            ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_label.setFont(font)
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.horizontalLayout_2.addWidget(self.main_label)
        self.main_lineEdit_age = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.main_lineEdit_age.setFont(font)
        self.main_lineEdit_age.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.main_lineEdit_age.setAlignment(QtCore.Qt.AlignCenter)
        self.main_lineEdit_age.setDragEnabled(False)
        self.main_lineEdit_age.setObjectName("main_lineEdit_age")
        self.horizontalLayout_2.addWidget(self.main_lineEdit_age)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.main_btn_calculate = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.main_btn_calculate.setFont(font)
        self.main_btn_calculate.setObjectName("main_btn_calculate")
        self.horizontalLayout.addWidget(self.main_btn_calculate)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор возраста"))
        self.main_label.setText(_translate("MainWindow", "Введите Ваш возраст"))
        self.main_btn_calculate.setText(_translate("MainWindow", "Вычислить"))
