# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(180, 85)
        MainWindow.setStyleSheet(u"QWidget {\n"
                                 "                color: black;\n"
                                 "                background-color: #FFF;\n"
                                 "                font-family: Rubik;\n"
                                 "                font-size: 14pt;\n"
                                 "                font-weight: 300;\n"
                                 "                }\n" 
                                 "            ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loading_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.loading_label.setFont(font)
        self.loading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.loading_label.setObjectName("loading_label")
        self.verticalLayout.addWidget(self.loading_label)
        self.loading_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.loading_progressBar.setProperty("value", 0)
        self.loading_progressBar.setObjectName("loading_progressBar")
        self.verticalLayout.addWidget(self.loading_progressBar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вычисление"))
        self.loading_label.setText(_translate("MainWindow", "Подсчёт данных"))
